# Generated by Django 2.2.3 on 2019-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField(max_length=200, unique=True)),
                ('party', models.CharField(choices=[('apc', 'APC'), ('apga', 'APGA'), ('pdc', 'PDC'), ('pdm', 'PDM'), ('pdp', 'PDP'), ('sdc', 'SDC')], default='select_your_party', max_length=100)),
            ],
            options={
                'db_table': 'voteresult',
                'ordering': ['-card_no'],
            },
        ),
    ]
