# Generated by Django 2.2.3 on 2019-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0004_voteresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegFm',
        ),
        migrations.AlterModelOptions(
            name='voteresult',
            options={'ordering': ['party']},
        ),
    ]
