# Generated by Django 2.2.3 on 2019-09-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0007_votecast_votereg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegFm',
        ),
        migrations.AlterUniqueTogether(
            name='votecast',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='votecast',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votecast',
            name='votereg_id',
        ),
        migrations.RemoveField(
            model_name='votereg',
            name='user',
        ),
        migrations.DeleteModel(
            name='VoteResult',
        ),
        migrations.DeleteModel(
            name='VoteCast',
        ),
        migrations.DeleteModel(
            name='VoteReg',
        ),
    ]
