# Generated by Django 2.2.3 on 2019-09-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0010_delete_votecast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegFm',
        ),
        migrations.DeleteModel(
            name='VoteResult',
        ),
    ]
