# Generated by Django 2.2.3 on 2019-09-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votingapp', '0011_auto_20190927_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=19, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100)),
                ('birthdate', models.DateField(default='0000-01-31')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], default='single', max_length=100)),
                ('home_town', models.CharField(max_length=255)),
                ('lga_of_origin', models.CharField(max_length=255)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voter_reg_form',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(choices=[('apc', 'APC'), ('apga', 'APGA'), ('pdc', 'PDC'), ('pdm', 'PDM'), ('pdp', 'PDP'), ('sdc', 'SDC')], default='apc', max_length=50)),
                ('date_voted', models.DateTimeField(auto_now_add=True)),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingapp.Voters')),
            ],
            options={
                'db_table': 'voteresult',
                'ordering': ['party'],
            },
        ),
    ]
