# Generated by Django 2.2.3 on 2019-09-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0012_vote_voters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Voters',
        ),
    ]
