# Generated by Django 2.2.3 on 2019-09-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0014_vote_voters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
